import type { Knex } from 'knex';

/**
 * Migration 007: Facial Templates
 *
 * Stores facial recognition data (embeddings/feature vectors) for
 * each employee. Used during check-in/out to verify the person
 * punching is actually the employee they claim to be.
 *
 * Design decisions:
 * - template_data: stores the facial embedding vector as JSONB.
 *   The embedding is a float array (typically 128–512 dimensions)
 *   generated by the facial recognition model.
 * - model_version: tracks which ML model generated the template,
 *   critical for migration when models are upgraded.
 * - quality_score: 0.0–1.0 assessment of the source image quality
 *   (lighting, angle, resolution) — low-quality templates can be
 *   flagged for re-capture.
 * - is_active: allows disabling a template without deleting it.
 * - One active template per employee enforced at application level
 *   (not DB constraint, to allow storing historical templates).
 * - image_count: how many source images were used to generate the
 *   template (more images = better accuracy).
 */
export async function up(knex: Knex): Promise<void> {
  await knex.schema.createTable('facial_templates', (t) => {
    t.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'));
    t.uuid('employee_id').notNullable().references('id').inTable('employees').onDelete('CASCADE');

    t.jsonb('template_data').notNullable();
    // Float array embedding vector, e.g. [0.123, -0.456, ...]

    t.string('model_version', 50).notNullable();
    // e.g. "facenet-v1", "arcface-r100"

    t.decimal('quality_score', 4, 3).nullable(); // 0.000–1.000
    t.integer('image_count').defaultTo(1);

    t.boolean('is_active').defaultTo(true);
    t.timestamp('created_at').defaultTo(knex.fn.now());
    t.timestamp('updated_at').defaultTo(knex.fn.now());
  });

  await knex.schema.raw(`
    CREATE INDEX idx_facial_employee ON facial_templates(employee_id);
    CREATE INDEX idx_facial_active ON facial_templates(employee_id, is_active)
      WHERE is_active = true;
  `);
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.dropTableIfExists('facial_templates');
}